### ISSUE TITLE
How to acquire data from a dynamic content page?

### ISSUE THREAD

**Issue by tezktenr** [JiJiU33C43I/UCI-Schedule-Assistant#1]
The "Schedule of Classes" page is dynamic, meaning user submitting forms and pages respond to user's actions. In that case, the URL of the page remains the same. How should data be fetched in this dynamic page?

**Comment by Jasonhx612** [comment]
A forward is performed server side and a redirect is performed client side.

When you forward something, the server forwards the request to another server/page and allows them to handle the request. This can be totally transparent as far as the client is concerned and even mask the URL. If you forward example.com to example.net then the end user will still see example.com in the address bar whilst actually browsing example.net

When you redirect, you issue a response back to the client telling them to go elsewhere. If the user navigates to example.com and you redirect them to example.net, you generally send a 30x response with the address you want them to go to. The user's browser then makes a second request to example.net and navigates there manually.

**Comment by tezktenr** [comment]
This is a kind of dynamic webpage called AJAX. It's a kind of webpage that actually uses javascript to retrieve data rather than the usual webpage that request a entire new webpage. 

In principle, users interact with the page, enter data or fill in forms, and the browser would take the input users enter and pass it as an argument to tha javascript written inside the page source. Then, the javascript inside the page source would run and update the text value of that SAME page (the URL doesnt change because this is NOT requesting an entire new page).

I believe the key to understand and solve this problem would be to understand javascript and learn it step by step from the beginning. BTW, the actual script inside the page source can be found within the script tag (<script>.....</script>). We should try to understand every script in the page source and use python to pass our inputs/arguments to that script and make it run.

Potential solution may be found by using external python libraries that could help us execute javascript in the webpage. Examples would be Selenium or mechanize, etc. More research need to be done. Watching some Youtube videos could help.

* Keywords that might be helpful for this issue: "Web scrape dynamic page", "Web scrape AJAX page", "execute javascript on website using python"

**Comment by tezktenr** [comment]
I just analyze the page source of "schedule of classes". I found out that this page is not using local javascript. Instead, it uses the form tag of html to POST data to the server and the server has that javascript and will run after taking inputs from that POSTed data. We should understand the form tag. 
More information: https://www.w3schools.com/html/html_forms.asp 

Solutions could be our python program sending/POSTing data to the server and get back the updated page and scrape the data there.

**Comment by tezktenr** [comment]
I think I figure out how to solve the issue.

Solution would be to use:

Page= urllib.request.urlopen("schedule of classes url", data)
Print(Page.read())

# data would be a dictionary that contains the data for users input
# for example, looking at the page source that collect the 'year term'.
Format: Data = {"NAME of that html tag" : "VALUE of options"}
E.g. Data = {"YearTerm" : "2019-03"}

Someone tried it out pls and give feedback in tjis post.
