### ISSUE TITLE
The best way to extract data from the page source

### ISSUE THREAD

**Issue by tezktenr** [JiJiU33C43I/UCI-Schedule-Assistant#3]
Having analyzed the page source, I found out that there are no attributes in the tags that contain the actual course data (e.g. course max enroll number, etc). What would be the best way to extract data in this case?

**Comment by lyz9518** [comment]
![webreg_data_tag](https://user-images.githubusercontent.com/44278886/50266005-d8a97f80-045c-11e9-9705-6ec17ef6faf5.png)

Find the course num in the<tr> tag and trace down to the different tags in it by default order

**Comment by tezktenr** [comment]
This will for sure works if I am given the course number in advance. However, let's say we are in the situation that the users tried to see all the COMPSCI courses through our apps (At least, that's how schedule of classes page works. Users select the Quarter Term and the department. The web returns all the results of COMPSCI courses.) So, the case here is to find a way to iterate through **ALL** the <tr> tags that contains course number and the course info. The difficulty, however, is that there is NOT a strict rule that could limit my iteration of <tr> tag of just the course info (In other words, there are also other <tr> tags that is not aimed for containing course info and it would be hard for us to distinguish which is which). Currently, the only idea I have is to observe the pattern of the html page source. Then, I can use the "next_sibling" method to get a way for us to ONLY iterate through the <tr> tags that contains COURSE INFORMATION and exclude ALL the other IRRELEVANT <tr> tags. However, this would be such an inefficient and INSECURE way since it depends on the pattern of the html page source. Once the page source is changed somehow in the future, our code will die and won't work. Not an ELEGANT solution. Any idea on that?

**Comment by tezktenr** [comment]
Web scraping engine has been uploaded. You might find the source code in **/src/web_scrape_engine.py**. Please carefully review the code and talk to me privately if you have any doubts or question. This issue will be closed. Instead, a new issue about optimizing will be created. Click to [go to the new issue](https://github.com/JiJiU33C43I/UCI-Schedule-Assistant/issues/5) here.
